/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class AktivaceNeaktivnichSlov extends javax.swing.JPanel {
private Gui gui;


    /**
     * Creates new form AktivaceNeaktivnichSlov
     */
    public AktivaceNeaktivnichSlov(Gui gui) {
this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aktivaceSlovicek12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        zobrazeniAktivaceSlovicek = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        aktivovatVse = new javax.swing.JButton();
        aktivovatVybrane = new javax.swing.JButton();
        coAktivovat = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        cleanAktivaceSlovicek = new javax.swing.JButton();

        aktivaceSlovicek12.setBackground(new java.awt.Color(51, 102, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 0));
        jLabel18.setText("Aktivace slovíček");

        zobrazeniAktivaceSlovicek.setEditable(false);
        zobrazeniAktivaceSlovicek.setBackground(new java.awt.Color(0, 0, 204));
        zobrazeniAktivaceSlovicek.setColumns(20);
        zobrazeniAktivaceSlovicek.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zobrazeniAktivaceSlovicek.setForeground(new java.awt.Color(0, 204, 0));
        zobrazeniAktivaceSlovicek.setRows(5);
        jScrollPane3.setViewportView(zobrazeniAktivaceSlovicek);

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setForeground(new java.awt.Color(0, 204, 0));
        jButton5.setText("Zpět");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        aktivovatVse.setBackground(new java.awt.Color(0, 0, 204));
        aktivovatVse.setForeground(new java.awt.Color(0, 204, 0));
        aktivovatVse.setText("Aktivovat vše");
        aktivovatVse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVseActionPerformed(evt);
            }
        });

        aktivovatVybrane.setBackground(new java.awt.Color(0, 0, 204));
        aktivovatVybrane.setForeground(new java.awt.Color(0, 204, 0));
        aktivovatVybrane.setText("Aktivovat vybrané");
        aktivovatVybrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVybraneActionPerformed(evt);
            }
        });

        coAktivovat.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setForeground(new java.awt.Color(0, 204, 0));
        jButton4.setText("Zobrazit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cleanAktivaceSlovicek.setBackground(new java.awt.Color(0, 0, 204));
        cleanAktivaceSlovicek.setForeground(new java.awt.Color(0, 204, 0));
        cleanAktivaceSlovicek.setText("Vyčisti");
        cleanAktivaceSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanAktivaceSlovicekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aktivaceSlovicek12Layout = new javax.swing.GroupLayout(aktivaceSlovicek12);
        aktivaceSlovicek12.setLayout(aktivaceSlovicek12Layout);
        aktivaceSlovicek12Layout.setHorizontalGroup(
            aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(cleanAktivaceSlovicek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(aktivovatVse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(coAktivovat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(aktivovatVybrane))
                    .addComponent(jScrollPane3)
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aktivaceSlovicek12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(101, 101, 101))
        );
        aktivaceSlovicek12Layout.setVerticalGroup(
            aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanAktivaceSlovicek)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktivovatVybrane)
                    .addComponent(coAktivovat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aktivovatVse))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aktivaceSlovicek12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aktivaceSlovicek12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.gui.setMyView(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void aktivovatVseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVseActionPerformed
        this.gui.slovnik.aktivaceDeaktivaceSlova(0, 1);
        JOptionPane.showMessageDialog(this.gui, "Vsechna slova byla aktivovana");
    }//GEN-LAST:event_aktivovatVseActionPerformed

    private void aktivovatVybraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVybraneActionPerformed
        if ((Integer) this.coAktivovat.getValue() > this.gui.slovnik.neaktivni.size()) {
            JOptionPane.showMessageDialog(this.gui, "Zadana dvojce slovicek neexistuje", "Chyba!", JOptionPane.WARNING_MESSAGE);
        } else {
            this.gui.slovnik.aktivaceDeaktivaceSlova((Integer) this.coAktivovat.getValue(), 1);
            JOptionPane.showMessageDialog(this.gui, "Aktivovano");
        }
    }//GEN-LAST:event_aktivovatVybraneActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (this.gui.slovnik.neaktivni.isEmpty()) {
            JOptionPane.showMessageDialog(this.gui, "Nejsou zadna slova ktere by bylo mozne aktivovat");
        } else {
            String[] slova = this.gui.slovnik.vypisNeaktivni();
            int citac = 1;
            for (int i = 0; i < slova.length; i++) {
                this.zobrazeniAktivaceSlovicek.append("(" + (citac) + ")" + slova[i] + "\n");
                citac++;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cleanAktivaceSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanAktivaceSlovicekActionPerformed
        this.zobrazeniAktivaceSlovicek.setText("");
    }//GEN-LAST:event_cleanAktivaceSlovicekActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aktivaceSlovicek12;
    private javax.swing.JButton aktivovatVse;
    private javax.swing.JButton aktivovatVybrane;
    private javax.swing.JButton cleanAktivaceSlovicek;
    private javax.swing.JSpinner coAktivovat;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea zobrazeniAktivaceSlovicek;
    // End of variables declaration//GEN-END:variables
}
