/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class AktivaceNeaktivnichSlov extends javax.swing.JPanel {
Slovník slovnik;
Gui gui;


    /**
     * Creates new form AktivaceNeaktivnichSlov
     */
    public AktivaceNeaktivnichSlov(Slovník slovnik, Gui gui) {
this.slovnik=slovnik;
this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aktivaceSlovicek12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        zobrazeniAktivaceSlovicek = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        aktivovatVse = new javax.swing.JButton();
        aktivovatVybrane = new javax.swing.JButton();
        coAktivovat = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        cleanAktivaceSlovicek = new javax.swing.JButton();

        jLabel18.setText("Aktivace slovicek");

        zobrazeniAktivaceSlovicek.setEditable(false);
        zobrazeniAktivaceSlovicek.setColumns(20);
        zobrazeniAktivaceSlovicek.setRows(5);
        jScrollPane3.setViewportView(zobrazeniAktivaceSlovicek);

        jButton5.setText("Zpet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Prejit do Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        aktivovatVse.setText("Aktivovat vse");
        aktivovatVse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVseActionPerformed(evt);
            }
        });

        aktivovatVybrane.setText("Aktivovat vybrane");
        aktivovatVybrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVybraneActionPerformed(evt);
            }
        });

        coAktivovat.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton4.setText("Zobraz");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cleanAktivaceSlovicek.setText("Vycisti");
        cleanAktivaceSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanAktivaceSlovicekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aktivaceSlovicek12Layout = new javax.swing.GroupLayout(aktivaceSlovicek12);
        aktivaceSlovicek12.setLayout(aktivaceSlovicek12Layout);
        aktivaceSlovicek12Layout.setHorizontalGroup(
            aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(cleanAktivaceSlovicek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4))
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(aktivovatVse)
                        .addGap(18, 18, 18)
                        .addComponent(coAktivovat)
                        .addGap(18, 18, 18)
                        .addComponent(aktivovatVybrane))
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aktivaceSlovicek12Layout.setVerticalGroup(
            aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aktivaceSlovicek12Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aktivaceSlovicek12Layout.createSequentialGroup()
                        .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(cleanAktivaceSlovicek))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aktivovatVse)
                            .addComponent(aktivovatVybrane))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(aktivaceSlovicek12Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(coAktivovat)))
                .addGap(18, 18, 18)
                .addGroup(aktivaceSlovicek12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aktivaceSlovicek12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aktivaceSlovicek12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.gui.setMyView(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.gui.setMyView(3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void aktivovatVseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVseActionPerformed
        this.slovnik.aktivaceDeaktivaceSlova(0, 1);
        JOptionPane.showMessageDialog(this.gui, "Vsechna slova byla aktivovana");
    }//GEN-LAST:event_aktivovatVseActionPerformed

    private void aktivovatVybraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVybraneActionPerformed
        if ((Integer) this.coAktivovat.getValue() > this.slovnik.neaktivni.size()) {
            JOptionPane.showMessageDialog(this.gui, "Zadana dvojce slovicek neexistuje", "Chyba!", JOptionPane.WARNING_MESSAGE);
        } else {
            this.slovnik.aktivaceDeaktivaceSlova((Integer) this.coAktivovat.getValue(), 1);
            JOptionPane.showMessageDialog(this.gui, "Aktivovano");
        }
    }//GEN-LAST:event_aktivovatVybraneActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (this.slovnik.neaktivni.isEmpty()) {
            JOptionPane.showMessageDialog(this.gui, "Nejsou zadna slova ktere by bylo mozne aktivovat");
        } else {
            String[] slova = this.slovnik.vypisNeaktivni();
            int citac = 1;
            for (int i = 0; i < slova.length; i++) {
                this.zobrazeniAktivaceSlovicek.append("(" + (citac) + ")" + slova[i] + "\n");
                citac++;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cleanAktivaceSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanAktivaceSlovicekActionPerformed
        this.zobrazeniAktivaceSlovicek.setText("");
    }//GEN-LAST:event_cleanAktivaceSlovicekActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aktivaceSlovicek12;
    private javax.swing.JButton aktivovatVse;
    private javax.swing.JButton aktivovatVybrane;
    private javax.swing.JButton cleanAktivaceSlovicek;
    private javax.swing.JSpinner coAktivovat;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea zobrazeniAktivaceSlovicek;
    // End of variables declaration//GEN-END:variables
}
