/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import java.awt.GridLayout;

/**
 *
 * @author Marco
 */
public class Gui extends javax.swing.JFrame {
    public int [] nasatveniTestu;
    public int [] spatneOdpovedi;
    Uzivatel uzivatel = new Uzivatel(this.rootPane);
    Slovník slovnik = new Slovník(this.rootPane);
    private static Gui myFrame;

    /**
     * Metoda která přepíná jednotlivé Jpanely. Parametrem panel se urci ktery 
     * panel se ma nastavit.
     *
     * @param panel
     * 1- Prihlaseni; 2- VyberSlovnik; 3- Menu; 4- VytvorNovyUcet;
     * 5- SpravaSlovicek; 6- PridaniSlovicek; 7- SmazaniSlovicek;
     * 8- ZobrazeniSlovicek; 9- ZobrazeniNeaktivnichSlovicek;
     * 10-AktivaceNeaktivnichSlov; 11- Statistiky; 
     * 12- NastaveniTestu; 13- Test; 14- VyhodnoceniTestu;
     * 15- SpravaSlovniku; 16- ZobrazeniSlovniku;
     * 17 - NovySlovnik; 18- SmazaniSlovniku;
     * 19-SpravaUzivatelu; 20 -ZmenaHesla;
     * 21-SmazaniUzivatele;
     */
    public void setMyView(int panel) {
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new GridLayout(1, 1, 1, 1));
        switch (panel) {
            case 1:
                this.jPanel1 = new Prihlaseni(myFrame);
                break;
            case 2:
                this.jPanel1 = new VyberSlovnik(myFrame);
                break;
            case 3:
                this.jPanel1 = new Menu(myFrame);
                break;
            case 4:
                this.jPanel1= new VytvorNovyUcet(myFrame);
                break;
            case 5:
                this.jPanel1 = new SpravaSlovicek(myFrame);
                break;
            case 6:
                this.jPanel1= new PridaniSlovicek(myFrame);
                break;
            case 7:
                this.jPanel1= new SmazaniSlovicek(myFrame);
                break;
            case 8:
                this.jPanel1 = new ZobrazeniSlovicek(myFrame);
                break;
            case 9:
                this.jPanel1=new ZobrazeniNeaktivnichSlovicek(myFrame);
                break;
            case 10:
                this.jPanel1=new AktivaceNeaktivnichSlov(myFrame);
                break;
            case 11:
                this.jPanel1= new Statistiky(myFrame);
                break;
            case 12:
                this.jPanel1= new NastaveniTestu(myFrame);
                break;
            case 13:
                this.jPanel1= new Test(myFrame);
                break;
            case 14 :
                this.jPanel1= new VyhodnoceniTestu(myFrame);
                break;
            case 15:
                this.jPanel1= new SpravaSlovniku(myFrame);
                break;
            case 16:
                this.jPanel1= new ZobrazeniSlovniku(myFrame);
                break;
            case 17:
                this.jPanel1= new NovySlovnik(myFrame);
                break;
            case 18:
                this.jPanel1= new SmazaniSlovniku(myFrame);
                break;
            case 19 :
                this.jPanel1= new SpravaUzivatelu(myFrame);
                break;
            case 20:
                this.jPanel1= new ZmenaHesla(myFrame);
                break;
            case 21:
                this.jPanel1= new SmazaniUzivatelu(myFrame);
                break;
                
        }
        jPanel1.setSize(jPanel1.getPreferredSize());
        this.getContentPane().add(jPanel1);
        this.getContentPane().setSize(jPanel1.getPreferredSize());
        pack();

    }

    /**
     * Creates new form Gui
     */
    public Gui() {
        this.setTitle("Slovnik");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Gui.myFrame = new Gui();
                Gui.myFrame.setMyView(1);
                Gui.myFrame.setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
