/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import java.awt.GridLayout;
import java.lang.reflect.Method;
import javax.swing.JFrame;
import javax.swing.JRootPane;

/**
 *
 * @author Marco
 */
public class Menu extends javax.swing.JPanel {
  private Gui frame;
  Hrac hrac;
    Slovník slovnik;
    /**
     * Creates new form Menu
     */
    public Menu(Gui frame) {
        this.frame=frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Zkouseni = new javax.swing.JButton();
        spravaSlovicekButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        zmenaSlovniku = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        odhlasitSe = new javax.swing.JButton();
        ukoncitProgram = new javax.swing.JButton();

        Menu.setBackground(new java.awt.Color(0, 102, 204));
        Menu.setPreferredSize(new java.awt.Dimension(370, 310));

        Zkouseni.setBackground(new java.awt.Color(0, 0, 204));
        Zkouseni.setForeground(new java.awt.Color(0, 204, 0));
        Zkouseni.setText("Zkouseni");
        Zkouseni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZkouseniActionPerformed(evt);
            }
        });

        spravaSlovicekButton.setBackground(new java.awt.Color(0, 0, 204));
        spravaSlovicekButton.setForeground(new java.awt.Color(0, 204, 0));
        spravaSlovicekButton.setText("Sprava slovicek");
        spravaSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spravaSlovicekButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setText("Statistiky");
        jButton3.setMaximumSize(new java.awt.Dimension(146, 46));
        jButton3.setMinimumSize(new java.awt.Dimension(146, 46));

        zmenaSlovniku.setBackground(new java.awt.Color(0, 0, 204));
        zmenaSlovniku.setForeground(new java.awt.Color(0, 204, 0));
        zmenaSlovniku.setText("Zmena slovniku");
        zmenaSlovniku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmenaSlovnikuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Menu");

        odhlasitSe.setBackground(new java.awt.Color(0, 0, 204));
        odhlasitSe.setForeground(new java.awt.Color(0, 204, 0));
        odhlasitSe.setText("Odhlsit se");
        odhlasitSe.setMaximumSize(new java.awt.Dimension(107, 23));
        odhlasitSe.setMinimumSize(new java.awt.Dimension(107, 23));
        odhlasitSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odhlasitSeActionPerformed(evt);
            }
        });

        ukoncitProgram.setBackground(new java.awt.Color(0, 0, 204));
        ukoncitProgram.setForeground(new java.awt.Color(0, 204, 0));
        ukoncitProgram.setText("Ukoncit program");
        ukoncitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukoncitProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Zkouseni, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spravaSlovicekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odhlasitSe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zmenaSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ukoncitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zkouseni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spravaSlovicekButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(zmenaSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(odhlasitSe, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(ukoncitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spravaSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spravaSlovicekButtonActionPerformed
        this.Menu.setVisible(false);
      
    }//GEN-LAST:event_spravaSlovicekButtonActionPerformed

    private void zmenaSlovnikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmenaSlovnikuActionPerformed
        this.slovnik.vycistiSpojovySeznam();
        this.Menu.setVisible(false);
    }//GEN-LAST:event_zmenaSlovnikuActionPerformed

    private void odhlasitSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odhlasitSeActionPerformed
        this.slovnik.ulozSlovnik(this.hrac.getJmeno());
        this.slovnik.vycistiSpojovySeznam();
        this.Menu.setVisible(false);

    }//GEN-LAST:event_odhlasitSeActionPerformed

    private void ukoncitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukoncitProgramActionPerformed
        this.slovnik.ulozSlovnik(this.hrac.getJmeno());
        this.slovnik.vycistiSpojovySeznam();
        System.exit(0);
    }//GEN-LAST:event_ukoncitProgramActionPerformed

    private void ZkouseniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZkouseniActionPerformed
           
        
    }//GEN-LAST:event_ZkouseniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Zkouseni;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton odhlasitSe;
    private javax.swing.JButton spravaSlovicekButton;
    private javax.swing.JButton ukoncitProgram;
    private javax.swing.JButton zmenaSlovniku;
    // End of variables declaration//GEN-END:variables
}
