/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

/**
 *
 * @author Marco
 */
public class NovySlovnik extends javax.swing.JPanel {
Gui gui;
    /**
     * Creates new form NovySlovnik
     */
    public NovySlovnik(Gui gui) {
        initComponents();
        this.gui=gui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vytvoreniSlovniku = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        nazevNovehoSlovniku = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        vytvorNovySlovnik = new javax.swing.JButton();

        jLabel33.setText("Vytvoreni Slovniku");

        jLabel34.setText("Zadejte jmeno slovniku");

        jButton15.setText("Zpet");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        vytvorNovySlovnik.setText("Vytvorit");
        vytvorNovySlovnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorNovySlovnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vytvoreniSlovnikuLayout = new javax.swing.GroupLayout(vytvoreniSlovniku);
        vytvoreniSlovniku.setLayout(vytvoreniSlovnikuLayout);
        vytvoreniSlovnikuLayout.setHorizontalGroup(
            vytvoreniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                .addGroup(vytvoreniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(vytvorNovySlovnik))
                    .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                        .addGroup(vytvoreniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nazevNovehoSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel34))
                            .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel33)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        vytvoreniSlovnikuLayout.setVerticalGroup(
            vytvoreniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vytvoreniSlovnikuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevNovehoSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(vytvoreniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(vytvorNovySlovnik))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vytvoreniSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vytvoreniSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
this.gui.setMyView(15);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void vytvorNovySlovnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorNovySlovnikActionPerformed
        this.gui.slovnik.vytvorNovySlovnik(this.nazevNovehoSlovniku.getText());
    }//GEN-LAST:event_vytvorNovySlovnikActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JTextField nazevNovehoSlovniku;
    private javax.swing.JButton vytvorNovySlovnik;
    private javax.swing.JPanel vytvoreniSlovniku;
    // End of variables declaration//GEN-END:variables
}
