/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class PridaniSlovicek extends javax.swing.JPanel {
private Gui gui;

    /**
     * Creates new form PridaniSlovicek
     */
    public PridaniSlovicek(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pridaniSlovicekPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ceskyVyraz1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        anglickyVyraz1 = new javax.swing.JTextField();
        Uloz1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        pridaniSlovicekPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 0));
        jLabel22.setText("Přídání slovíček");

        jLabel23.setForeground(new java.awt.Color(0, 204, 0));
        jLabel23.setText("Zadejte český výraz :");

        ceskyVyraz1.setBackground(new java.awt.Color(0, 0, 204));
        ceskyVyraz1.setForeground(new java.awt.Color(0, 204, 0));
        ceskyVyraz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceskyVyraz1ActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(0, 204, 0));
        jLabel24.setText("Zadejte jeho anglický překlad :");

        anglickyVyraz1.setBackground(new java.awt.Color(0, 0, 204));
        anglickyVyraz1.setForeground(new java.awt.Color(0, 204, 0));

        Uloz1.setBackground(new java.awt.Color(0, 0, 204));
        Uloz1.setForeground(new java.awt.Color(0, 204, 0));
        Uloz1.setText("Ulož");
        Uloz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uloz1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Zpět");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pridaniSlovicekPanel1Layout = new javax.swing.GroupLayout(pridaniSlovicekPanel1);
        pridaniSlovicekPanel1.setLayout(pridaniSlovicekPanel1Layout);
        pridaniSlovicekPanel1Layout.setHorizontalGroup(
            pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pridaniSlovicekPanel1Layout.createSequentialGroup()
                .addGroup(pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pridaniSlovicekPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ceskyVyraz1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pridaniSlovicekPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(anglickyVyraz1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pridaniSlovicekPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Uloz1)))
                .addContainerGap())
            .addGroup(pridaniSlovicekPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pridaniSlovicekPanel1Layout.setVerticalGroup(
            pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pridaniSlovicekPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ceskyVyraz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(anglickyVyraz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pridaniSlovicekPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uloz1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pridaniSlovicekPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pridaniSlovicekPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ceskyVyraz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceskyVyraz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceskyVyraz1ActionPerformed

    private void Uloz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uloz1ActionPerformed
        this.gui.slovnik.vlozNaKonec(this.anglickyVyraz1.getText(), 
                this.ceskyVyraz1.getText(), 0, 0, 
                this.gui.slovnik.vytvorNoveIdSlova(), 1);
             JOptionPane.showMessageDialog(this.gui, "Vyraz byl ulozen");
        
    }//GEN-LAST:event_Uloz1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.gui.setMyView(5);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Uloz1;
    private javax.swing.JTextField anglickyVyraz1;
    private javax.swing.JTextField ceskyVyraz1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel pridaniSlovicekPanel1;
    // End of variables declaration//GEN-END:variables
}
