/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class Prihlaseni extends javax.swing.JPanel {
private Gui gui;
    /**
     * Creates new form Prihlaseni
     */
    public Prihlaseni(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prihlaseniPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vyberUcet = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        vstupHesla = new javax.swing.JPasswordField();
        vytvorNovyUcet = new javax.swing.JButton();
        prihlas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Vyberte svůj účet :");

        vyberUcet.setModel(new javax.swing.DefaultComboBoxModel(gui.uzivatel.nactiUdajeOHracich(1)));
        vyberUcet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberUcetActionPerformed(evt);
            }
        });

        jLabel2.setText("Zadejte své heslo");

        vytvorNovyUcet.setText("Vytvorit novy ucet");
        vytvorNovyUcet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorNovyUcetActionPerformed(evt);
            }
        });

        prihlas.setText("Prihlas");
        prihlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasActionPerformed(evt);
            }
        });

        jLabel3.setText("Přihlášení");

        javax.swing.GroupLayout prihlaseniPanelLayout = new javax.swing.GroupLayout(prihlaseniPanel);
        prihlaseniPanel.setLayout(prihlaseniPanelLayout);
        prihlaseniPanelLayout.setHorizontalGroup(
            prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prihlaseniPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prihlaseniPanelLayout.createSequentialGroup()
                        .addComponent(vytvorNovyUcet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prihlas))
                    .addGroup(prihlaseniPanelLayout.createSequentialGroup()
                        .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vstupHesla, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vyberUcet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prihlaseniPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
        );
        prihlaseniPanelLayout.setVerticalGroup(
            prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prihlaseniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vyberUcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vstupHesla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(prihlaseniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prihlas)
                    .addComponent(vytvorNovyUcet))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(prihlaseniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prihlaseniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vyberUcetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberUcetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vyberUcetActionPerformed

    private void vytvorNovyUcetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorNovyUcetActionPerformed
           this.gui.setMyView(4);
    }//GEN-LAST:event_vytvorNovyUcetActionPerformed

    private void prihlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasActionPerformed
        boolean spravne = gui.uzivatel.prihlaseni(this.vyberUcet.getSelectedItem().toString(), 
                String.valueOf(this.vstupHesla.getPassword()), this.vyberUcet.getSelectedIndex());
        if (spravne) {
           this.gui.setMyView(2);
        } else {
            JOptionPane.showMessageDialog(this.gui, "Bylo zadano spatne heslo, zbavaji vam " + (3 - this.gui.uzivatel.getPokusy()) + " pokusy",
                    "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_prihlasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton prihlas;
    private javax.swing.JPanel prihlaseniPanel;
    private javax.swing.JPasswordField vstupHesla;
    private javax.swing.JComboBox vyberUcet;
    private javax.swing.JButton vytvorNovyUcet;
    // End of variables declaration//GEN-END:variables
}
