/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SmazaniSlovniku extends javax.swing.JPanel {
private Gui gui;
    /**
     * Creates new form SmazaniSlovniku
     */

private void  start(){
    ArrayList seznam=this.gui.slovnik.getSeznamSlovniku();
        for (int i = 0; i < seznam.size(); i++) {
            this.textAreaSmazaniSlovniku.append(""+seznam.get(i) +"\n");
}
}
    public SmazaniSlovniku(Gui gui) {
       this.gui=gui;
        initComponents();
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smazaniSlovniku = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaSmazaniSlovniku = new javax.swing.JTextArea();
        jButton16 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        spinnerSmazaniSlovniku = new javax.swing.JSpinner();
        vymazatSlovnik = new javax.swing.JButton();

        jLabel35.setText("Smazani Slovniku");

        textAreaSmazaniSlovniku.setEditable(false);
        textAreaSmazaniSlovniku.setColumns(20);
        textAreaSmazaniSlovniku.setRows(5);
        jScrollPane7.setViewportView(textAreaSmazaniSlovniku);

        jButton16.setText("Zpet");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel36.setText("Vybetre slovnik ke smazani:");

        spinnerSmazaniSlovniku.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        vymazatSlovnik.setText("Vymazat");
        vymazatSlovnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazatSlovnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smazaniSlovnikuLayout = new javax.swing.GroupLayout(smazaniSlovniku);
        smazaniSlovniku.setLayout(smazaniSlovnikuLayout);
        smazaniSlovnikuLayout.setHorizontalGroup(
            smazaniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smazaniSlovnikuLayout.createSequentialGroup()
                .addGroup(smazaniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smazaniSlovnikuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton16)
                        .addGap(26, 26, 26)
                        .addComponent(spinnerSmazaniSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vymazatSlovnik))
                    .addGroup(smazaniSlovnikuLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel35))
                    .addGroup(smazaniSlovnikuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smazaniSlovnikuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(57, 57, 57))
        );
        smazaniSlovnikuLayout.setVerticalGroup(
            smazaniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smazaniSlovnikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(smazaniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerSmazaniSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16)
                    .addComponent(vymazatSlovnik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smazaniSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smazaniSlovniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
this.gui.setMyView(15);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void vymazatSlovnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazatSlovnikActionPerformed
        if(this.gui.slovnik.getPocetSlovniku()<=((Integer)this.spinnerSmazaniSlovniku.getValue())){
           this.gui.slovnik.smazSlovnik((Integer)this.spinnerSmazaniSlovniku.getValue());
        }else{
            JOptionPane.showMessageDialog(this.gui, "Slovnik s timto cislem neexistuje!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_vymazatSlovnikActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel smazaniSlovniku;
    private javax.swing.JSpinner spinnerSmazaniSlovniku;
    private javax.swing.JTextArea textAreaSmazaniSlovniku;
    private javax.swing.JButton vymazatSlovnik;
    // End of variables declaration//GEN-END:variables
}
