/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SmazaniSlovicek extends javax.swing.JPanel {
private Gui gui;

    /**
     * Creates new form SmazaniSlovicek
     */

private void vypisSlova(){
    String[] slova = gui.slovnik.vypisSpojovySeznam();
        for (int i = 0; i < slova.length; i++) {
            this.jTextArea1.append("("+i+")"+slova[i] + "\n");
        }
    
}
    public SmazaniSlovicek(Gui gui) {
        this.gui=gui;
        initComponents();
        vypisSlova();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mazaniSlovicekPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deaktivujDvojci = new javax.swing.JButton();
        uplneVymazani = new javax.swing.JButton();
        zpetMazaniSlovicek = new javax.swing.JButton();
        cisloKeSmazani = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        mazaniSlovicekPanel.setBackground(new java.awt.Color(51, 102, 255));

        jLabel14.setBackground(new java.awt.Color(51, 102, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setText("Mazání slovíček");

        jLabel15.setForeground(new java.awt.Color(0, 204, 0));
        jLabel15.setText("Číslem vyberte dvojci slovíček ke smazání :");

        deaktivujDvojci.setBackground(new java.awt.Color(0, 0, 204));
        deaktivujDvojci.setForeground(new java.awt.Color(0, 204, 0));
        deaktivujDvojci.setText("Deaktivivat dvojci");
        deaktivujDvojci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deaktivujDvojciActionPerformed(evt);
            }
        });

        uplneVymazani.setBackground(new java.awt.Color(0, 0, 204));
        uplneVymazani.setForeground(new java.awt.Color(0, 204, 0));
        uplneVymazani.setText("Úplné vymazání");
        uplneVymazani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplneVymazaniActionPerformed(evt);
            }
        });

        zpetMazaniSlovicek.setBackground(new java.awt.Color(0, 0, 204));
        zpetMazaniSlovicek.setForeground(new java.awt.Color(0, 204, 0));
        zpetMazaniSlovicek.setText("Zpět");
        zpetMazaniSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetMazaniSlovicekActionPerformed(evt);
            }
        });

        cisloKeSmazani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cisloKeSmazani.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 204, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Zobrazit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mazaniSlovicekPanelLayout = new javax.swing.GroupLayout(mazaniSlovicekPanel);
        mazaniSlovicekPanel.setLayout(mazaniSlovicekPanelLayout);
        mazaniSlovicekPanelLayout.setHorizontalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mazaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(87, 87, 87))
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addComponent(cisloKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(deaktivujDvojci)
                        .addGap(18, 18, 18)
                        .addComponent(uplneVymazani))
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addComponent(zpetMazaniSlovicek)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        mazaniSlovicekPanelLayout.setVerticalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(23, 23, 23)
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deaktivujDvojci)
                    .addComponent(cisloKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uplneVymazani))
                .addGap(18, 18, 18)
                .addComponent(zpetMazaniSlovicek)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deaktivujDvojciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deaktivujDvojciActionPerformed
        int volba;
        if (((Integer) this.cisloKeSmazani.getValue()) > gui.slovnik.getPocetBunek()) {
            JOptionPane.showMessageDialog(this.gui, "Zadana dvojce neexistuje", "Chyba", JOptionPane.WARNING_MESSAGE);
        } else {
            volba = JOptionPane.showConfirmDialog(this.gui, "Opravdu chcete deaktivovat dvojci slovicek "
                + this.gui.slovnik.getObsahBunky((Integer) this.cisloKeSmazani.getValue(),7), "Chyba!", JOptionPane.YES_NO_OPTION);

            if (volba == 0) {
                this.gui.slovnik.aktivaceDeaktivaceSlova((Integer) this.cisloKeSmazani.getValue(), volba);
                this.gui.slovnik.presunNeaktivni();
                JOptionPane.showMessageDialog(this.gui, "Dvojce slovicek byla deaktivovana");
            } else {
                JOptionPane.showMessageDialog(this.gui, "Dvojce slovicek nebyla deaktivovana");
            }
        }
    }//GEN-LAST:event_deaktivujDvojciActionPerformed

    private void uplneVymazaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplneVymazaniActionPerformed
        int volba;
        if (this.gui.uzivatel.testPravomoc(this.gui.slovnik.getTvurceSlovniku(), 3)) {
            if (((Integer) this.cisloKeSmazani.getValue()) > gui.slovnik.getPocetBunek()) {
                JOptionPane.showMessageDialog(this.gui, "Zadana dvojce neexistuje", "Chyba", JOptionPane.WARNING_MESSAGE);
            } else {
                volba = JOptionPane.showConfirmDialog(this.gui, "Opravdu chcete smazat dvojci slovicek"
                    + this.gui.slovnik.getObsahBunky((Integer) this.cisloKeSmazani.getValue(),7), "Chyba!", JOptionPane.YES_NO_OPTION);
                if (volba == 0) {
                    this.gui.slovnik.smaz((Integer) this.cisloKeSmazani.getValue());
                    JOptionPane.showMessageDialog(this.gui, "Dvojce byla smazana");
                } else {
                    JOptionPane.showMessageDialog(this.gui, "Dvojce nebyla smazana");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this.gui, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_uplneVymazaniActionPerformed

    private void zpetMazaniSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetMazaniSlovicekActionPerformed
        this.gui.setMyView(5);
    }//GEN-LAST:event_zpetMazaniSlovicekActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.vypisSlova();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cisloKeSmazani;
    private javax.swing.JButton deaktivujDvojci;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mazaniSlovicekPanel;
    private javax.swing.JButton uplneVymazani;
    private javax.swing.JButton zpetMazaniSlovicek;
    // End of variables declaration//GEN-END:variables
}
