/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SmazaniSlovicek extends javax.swing.JPanel {
Slovník slovnik;
Uzivatel uzivatel;
private Gui gui;

    /**
     * Creates new form SmazaniSlovicek
     */
    public SmazaniSlovicek(Slovník slovnik, Uzivatel hrac,Gui frame) {
           this.slovnik=slovnik;
        this.uzivatel=hrac;
        this.gui=frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mazaniSlovicekPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        deaktivujDvojci = new javax.swing.JButton();
        uplneVymazani = new javax.swing.JButton();
        zpetMazaniSlovicek = new javax.swing.JButton();
        cisloKeSmazani = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        jLabel14.setText("Mazani Slovicek");

        jLabel15.setText("Cislem vyberete dvojci slovicek ke smazani.");

        jLabel16.setText("Pred provedenim akce se dana dvojce slovicek zabrazi.");

        deaktivujDvojci.setText("deaktivivat dvojci");
        deaktivujDvojci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deaktivujDvojciActionPerformed(evt);
            }
        });

        uplneVymazani.setText("Uplne Vymazani");
        uplneVymazani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplneVymazaniActionPerformed(evt);
            }
        });

        zpetMazaniSlovicek.setText("Zpet");
        zpetMazaniSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetMazaniSlovicekActionPerformed(evt);
            }
        });

        cisloKeSmazani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cisloKeSmazani.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton1.setText("Preji do Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mazaniSlovicekPanelLayout = new javax.swing.GroupLayout(mazaniSlovicekPanel);
        mazaniSlovicekPanel.setLayout(mazaniSlovicekPanelLayout);
        mazaniSlovicekPanelLayout.setHorizontalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                                    .addComponent(cisloKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deaktivujDvojci))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mazaniSlovicekPanelLayout.createSequentialGroup()
                                    .addComponent(zpetMazaniSlovicek)
                                    .addGap(19, 19, 19)
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(uplneVymazani)))))
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mazaniSlovicekPanelLayout.setVerticalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cisloKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deaktivujDvojci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zpetMazaniSlovicek)
                    .addComponent(jButton1)
                    .addComponent(uplneVymazani))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deaktivujDvojciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deaktivujDvojciActionPerformed
        int volba;
        volba = 0;
        if (((Integer) this.cisloKeSmazani.getValue()) > slovnik.getPocetBunek()) {
            JOptionPane.showMessageDialog(this.gui, "Zadana dvojce neexistuje", "Chyba", JOptionPane.WARNING_MESSAGE);
        } else {
            volba = JOptionPane.showConfirmDialog(this.gui, "Opravdu chcete deaktivovat dvojci slovicek "
                + this.slovnik.vypisXZeSpojovehoSeznamu((Integer) this.cisloKeSmazani.getValue()), "Chyba!", JOptionPane.YES_NO_OPTION);

            if (volba == 0) {
                this.slovnik.aktivaceDeaktivaceSlova((Integer) this.cisloKeSmazani.getValue(), volba);
                this.slovnik.presunNeaktivni();
                JOptionPane.showMessageDialog(this.gui, "Dvojce slovicek byla deaktivovana");
            } else {
                JOptionPane.showMessageDialog(this.gui, "Dvojce slovicek nebyla deaktivovana");
            }
        }
    }//GEN-LAST:event_deaktivujDvojciActionPerformed

    private void uplneVymazaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplneVymazaniActionPerformed
        int volba;
        if (this.uzivatel.testPravomoc(this.slovnik.getTvurceSlovniku(), 3)) {
            if (((Integer) this.cisloKeSmazani.getValue()) > slovnik.getPocetBunek()) {
                JOptionPane.showMessageDialog(this.gui, "Zadana dvojce neexistuje", "Chyba", JOptionPane.WARNING_MESSAGE);
            } else {
                volba = JOptionPane.showConfirmDialog(this.gui, "Opravdu chcete smazat dvojci slovicek"
                    + this.slovnik.vypisXZeSpojovehoSeznamu((Integer) this.cisloKeSmazani.getValue()), "Chyba!", JOptionPane.YES_NO_OPTION);
                if (volba == 0) {
                    this.slovnik.smaz((Integer) this.cisloKeSmazani.getValue());
                    JOptionPane.showMessageDialog(this.gui, "Dvojce byla smazana");
                } else {
                    JOptionPane.showMessageDialog(this.gui, "Dvojce nebyla smazana");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this.gui, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_uplneVymazaniActionPerformed

    private void zpetMazaniSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetMazaniSlovicekActionPerformed
        this.gui.setMyView(5);
    }//GEN-LAST:event_zpetMazaniSlovicekActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.gui.setMyView(3);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cisloKeSmazani;
    private javax.swing.JButton deaktivujDvojci;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel mazaniSlovicekPanel;
    private javax.swing.JButton uplneVymazani;
    private javax.swing.JButton zpetMazaniSlovicek;
    // End of variables declaration//GEN-END:variables
}
