/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SpravaSlovicek extends javax.swing.JPanel {
private Gui gui;

    /**
     * Creates new form SpravaSlovicek
     */
    public SpravaSlovicek(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spravaSlovicek1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pridaniSlovicekButton1 = new javax.swing.JButton();
        smazaniSlovicekButton1 = new javax.swing.JButton();
        zobrazeniSlovicekButton1 = new javax.swing.JButton();
        zobrazeniNeaktivnichSlovicekButton1 = new javax.swing.JButton();
        zpetSpravaSlovicek = new javax.swing.JButton();
        aktivovaniNeaktivnichSlov1 = new javax.swing.JToggleButton();
        jLabel4 = new MyLabel(this.gui,3);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new MyLabel(this.gui,5);

        spravaSlovicek1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 0));
        jLabel21.setText("Správa slovíček");

        pridaniSlovicekButton1.setBackground(new java.awt.Color(0, 0, 204));
        pridaniSlovicekButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pridaniSlovicekButton1.setForeground(new java.awt.Color(0, 204, 0));
        pridaniSlovicekButton1.setText("Přídaní slovíček");
        pridaniSlovicekButton1.setMaximumSize(new java.awt.Dimension(75, 23));
        pridaniSlovicekButton1.setMinimumSize(new java.awt.Dimension(75, 23));
        pridaniSlovicekButton1.setPreferredSize(new java.awt.Dimension(75, 23));
        pridaniSlovicekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridaniSlovicekButton1ActionPerformed(evt);
            }
        });

        smazaniSlovicekButton1.setBackground(new java.awt.Color(0, 0, 204));
        smazaniSlovicekButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smazaniSlovicekButton1.setForeground(new java.awt.Color(0, 204, 0));
        smazaniSlovicekButton1.setText("Mazání slovíček");
        smazaniSlovicekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smazaniSlovicekButton1ActionPerformed(evt);
            }
        });

        zobrazeniSlovicekButton1.setBackground(new java.awt.Color(0, 0, 204));
        zobrazeniSlovicekButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zobrazeniSlovicekButton1.setForeground(new java.awt.Color(0, 204, 0));
        zobrazeniSlovicekButton1.setText("Zobrazení slovíček");
        zobrazeniSlovicekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniSlovicekButton1ActionPerformed(evt);
            }
        });

        zobrazeniNeaktivnichSlovicekButton1.setBackground(new java.awt.Color(0, 0, 204));
        zobrazeniNeaktivnichSlovicekButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zobrazeniNeaktivnichSlovicekButton1.setForeground(new java.awt.Color(0, 204, 0));
        zobrazeniNeaktivnichSlovicekButton1.setText("Zobrazení neaktivních slovíček");
        zobrazeniNeaktivnichSlovicekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniNeaktivnichSlovicekButton1ActionPerformed(evt);
            }
        });

        zpetSpravaSlovicek.setBackground(new java.awt.Color(0, 0, 204));
        zpetSpravaSlovicek.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zpetSpravaSlovicek.setForeground(new java.awt.Color(0, 204, 0));
        zpetSpravaSlovicek.setText("Zpět");
        zpetSpravaSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetSpravaSlovicekActionPerformed(evt);
            }
        });

        aktivovaniNeaktivnichSlov1.setBackground(new java.awt.Color(0, 0, 204));
        aktivovaniNeaktivnichSlov1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aktivovaniNeaktivnichSlov1.setForeground(new java.awt.Color(0, 204, 0));
        aktivovaniNeaktivnichSlov1.setText("Aktivace  slovíček");
        aktivovaniNeaktivnichSlov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovaniNeaktivnichSlov1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Menu");

        jLabel1.setText("-->");

        jLabel2.setText("Správa slovíček");

        javax.swing.GroupLayout spravaSlovicek1Layout = new javax.swing.GroupLayout(spravaSlovicek1);
        spravaSlovicek1.setLayout(spravaSlovicek1Layout);
        spravaSlovicek1Layout.setHorizontalGroup(
            spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spravaSlovicek1Layout.createSequentialGroup()
                                .addComponent(zobrazeniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(aktivovaniNeaktivnichSlov1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spravaSlovicek1Layout.createSequentialGroup()
                                .addComponent(pridaniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zobrazeniNeaktivnichSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                                .addComponent(zpetSpravaSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(smazaniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                        .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel21))
                            .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        spravaSlovicek1Layout.setVerticalGroup(
            spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicek1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(32, 32, 32)
                .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zobrazeniNeaktivnichSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pridaniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktivovaniNeaktivnichSlov1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zobrazeniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zpetSpravaSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smazaniSlovicekButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(spravaSlovicek1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spravaSlovicek1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spravaSlovicek1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pridaniSlovicekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridaniSlovicekButton1ActionPerformed
        if (this.gui.uzivatel.testPravomoc(this.gui.slovnik.getTvurceSlovniku(), 1)) {
          this.gui.setMyView(6);
        }
    }//GEN-LAST:event_pridaniSlovicekButton1ActionPerformed

    private void smazaniSlovicekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smazaniSlovicekButton1ActionPerformed
        if (this.gui.uzivatel.testPravomoc(this.gui.slovnik.getTvurceSlovniku(), 1)) {
        this.gui.setMyView(7);
        }
    }//GEN-LAST:event_smazaniSlovicekButton1ActionPerformed

    private void zobrazeniSlovicekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniSlovicekButton1ActionPerformed
if(this.gui.slovnik.getPocetBunek()==0){
     JOptionPane.showMessageDialog(this.gui, "Nejsou zadna slova k zobrazeni");
}else{
     this.gui.setMyView(8);  
}    
    }//GEN-LAST:event_zobrazeniSlovicekButton1ActionPerformed

    private void zobrazeniNeaktivnichSlovicekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniNeaktivnichSlovicekButton1ActionPerformed
if(this.gui.slovnik.neaktivni.size()==0){
     JOptionPane.showMessageDialog(this.gui, "Nejsou zadna slova k zobrazeni");
}else{
       this.gui.setMyView(9); 
}
        
             
    }//GEN-LAST:event_zobrazeniNeaktivnichSlovicekButton1ActionPerformed

    private void zpetSpravaSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetSpravaSlovicekActionPerformed
this.gui.setMyView(3);     
    }//GEN-LAST:event_zpetSpravaSlovicekActionPerformed

    private void aktivovaniNeaktivnichSlov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovaniNeaktivnichSlov1ActionPerformed
        if (this.gui.uzivatel.testPravomoc(this.gui.slovnik.getTvurceSlovniku(), 1)) {
            this.gui.setMyView(10);
        }
    }//GEN-LAST:event_aktivovaniNeaktivnichSlov1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aktivovaniNeaktivnichSlov1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton pridaniSlovicekButton1;
    private javax.swing.JButton smazaniSlovicekButton1;
    private javax.swing.JPanel spravaSlovicek1;
    private javax.swing.JButton zobrazeniNeaktivnichSlovicekButton1;
    private javax.swing.JButton zobrazeniSlovicekButton1;
    private javax.swing.JButton zpetSpravaSlovicek;
    // End of variables declaration//GEN-END:variables
}
