/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SpravaSlovicek extends javax.swing.JPanel {
    Slovník slovnik;
Uzivatel hrac;
private Gui gui;

    /**
     * Creates new form SpravaSlovicek
     */
    public SpravaSlovicek(Slovník slovnik, Uzivatel hrac,Gui frame) {
         this.slovnik=slovnik;
        this.hrac=hrac;
        this.gui=frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spravaSlovicek = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pridaniSlovicekButton = new javax.swing.JButton();
        smazaniSlovicekButton = new javax.swing.JButton();
        zobrazeniSlovicekButton = new javax.swing.JButton();
        zobrazeniNeaktivnichSlovicekButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        aktivovaniNeaktivnichSlov = new javax.swing.JToggleButton();

        spravaSlovicek.setBackground(new java.awt.Color(0, 102, 204));

        jLabel9.setText("Sprava Slovicek");

        pridaniSlovicekButton.setText("Pridani slovicek");
        pridaniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridaniSlovicekButtonActionPerformed(evt);
            }
        });

        smazaniSlovicekButton.setText("Smazani slovicek");
        smazaniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smazaniSlovicekButtonActionPerformed(evt);
            }
        });

        zobrazeniSlovicekButton.setText("Zobrazeni slovicek");
        zobrazeniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniSlovicekButtonActionPerformed(evt);
            }
        });

        zobrazeniNeaktivnichSlovicekButton.setText("Zobrazeni neaktivnich slovicek");
        zobrazeniNeaktivnichSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniNeaktivnichSlovicekButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Zpet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aktivovaniNeaktivnichSlov.setText("Aktivovat neaktivni slovicka");
        aktivovaniNeaktivnichSlov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovaniNeaktivnichSlovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout spravaSlovicekLayout = new javax.swing.GroupLayout(spravaSlovicek);
        spravaSlovicek.setLayout(spravaSlovicekLayout);
        spravaSlovicekLayout.setHorizontalGroup(
            spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addComponent(pridaniSlovicekButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(smazaniSlovicekButton)
                        .addGap(39, 39, 39))
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addComponent(zobrazeniSlovicekButton)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aktivovaniNeaktivnichSlov)
                            .addComponent(zobrazeniNeaktivnichSlovicekButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        spravaSlovicekLayout.setVerticalGroup(
            spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridaniSlovicekButton)
                    .addComponent(smazaniSlovicekButton))
                .addGap(18, 18, 18)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zobrazeniSlovicekButton)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(zobrazeniNeaktivnichSlovicekButton)
                .addGap(18, 18, 18)
                .addComponent(aktivovaniNeaktivnichSlov)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spravaSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spravaSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pridaniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridaniSlovicekButtonActionPerformed
        if (this.hrac.testPravomoc(this.slovnik.getTvurceSlovniku(), 2)) {
            
            
        } else {
            JOptionPane.showConfirmDialog(gui, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_pridaniSlovicekButtonActionPerformed

    private void smazaniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smazaniSlovicekButtonActionPerformed
        if (this.hrac.testPravomoc(this.slovnik.getTvurceSlovniku(), 1)) {
          
        } else {
            JOptionPane.showConfirmDialog(gui, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_smazaniSlovicekButtonActionPerformed

    private void zobrazeniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniSlovicekButtonActionPerformed
       
    }//GEN-LAST:event_zobrazeniSlovicekButtonActionPerformed

    private void zobrazeniNeaktivnichSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniNeaktivnichSlovicekButtonActionPerformed
      
    }//GEN-LAST:event_zobrazeniNeaktivnichSlovicekButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aktivovaniNeaktivnichSlovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovaniNeaktivnichSlovActionPerformed
        if (this.hrac.testPravomoc(this.slovnik.getTvurceSlovniku(), 1)) {
          
           
        } else {
            JOptionPane.showConfirmDialog(gui, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_aktivovaniNeaktivnichSlovActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aktivovaniNeaktivnichSlov;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton pridaniSlovicekButton;
    private javax.swing.JButton smazaniSlovicekButton;
    private javax.swing.JPanel spravaSlovicek;
    private javax.swing.JButton zobrazeniNeaktivnichSlovicekButton;
    private javax.swing.JButton zobrazeniSlovicekButton;
    // End of variables declaration//GEN-END:variables
}
