/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class StareGui extends javax.swing.JFrame {

    Uzivatel uzivatel = new Uzivatel();
    Slovník slovnik = new Slovník();
    Slovník neaktivni = new Slovník();

    /**
     * Creates new form StareGui
     */
    public StareGui() {
        initComponents();
        this.setTitle("Slovnik");
        this.setSize(250, 200);
        this.novyUcet.setVisible(false);
        this.vyberSlovnikPanel.setVisible(false);
        this.mazaniSlovicekPanel.setVisible(false);
        this.pridaniSlovicekPanel.setVisible(false);
        this.spravaSlovicek.setVisible(false);
        this.zobrazeniNeaktivnichSlovicek.setVisible(false);
        this.zobrazeniSlovicekPanel.setVisible(false);
        this.statistiky.setVisible(false);
        this.aktivaceSlovicek.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prihlaseni = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vyberUcet = new javax.swing.JComboBox();
        prihlas = new javax.swing.JButton();
        vytvorNovyUcet = new javax.swing.JButton();
        vstupHesla = new javax.swing.JPasswordField();
        novyUcet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vytvorUcetButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        zpetDoPrihlas = new javax.swing.JButton();
        jmenoUctu = new javax.swing.JTextField();
        hesloNovehoUctu = new javax.swing.JPasswordField();
        opakovaneHesloNovehoUctu = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        vyberSlovnikPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        vyberSlovnik = new javax.swing.JComboBox();
        potvrdSlovnik = new javax.swing.JButton();
        pridaniSlovicekPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ceskyVyraz = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        anglickyVyraz = new javax.swing.JTextField();
        Uloz = new javax.swing.JButton();
        spravaSlovicek = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pridaniSlovicekButton = new javax.swing.JButton();
        smazaniSlovicekButton = new javax.swing.JButton();
        zobrazeniSlovicekButton = new javax.swing.JButton();
        zobrazeniNeaktivnichSlovicekButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        aktivovaniNeaktivnichSlov = new javax.swing.JToggleButton();
        Menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        spravaSlovicekButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        zmenaSlovniku = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        odhlasitSe = new javax.swing.JButton();
        ukoncitProgram = new javax.swing.JButton();
        zobrazeniSlovicekPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        zobrayeniSlovicekText = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        zobrazVse = new javax.swing.JButton();
        zobrazZvolenouDvojci = new javax.swing.JButton();
        vyberSlovo = new javax.swing.JTextField();
        zobrazeniNeaktivnichSlovicek = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        zobrayVseNeaktivni = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        zobrayeniNeaktivnichSlov = new javax.swing.JTextArea();
        zpetNeaktivni = new javax.swing.JButton();
        prejitDoMenuNeaktivni = new javax.swing.JButton();
        mazaniSlovicekPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        slovickoKeSmazani = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Smaz = new javax.swing.JButton();
        uplneVymazani = new javax.swing.JButton();
        zpetMazaniSlovicek = new javax.swing.JButton();
        statistiky = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        aktivaceSlovicek = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        zobrayeniAktivaceSlovicek = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        aktivovatVse = new javax.swing.JButton();
        coAktovovat = new javax.swing.JTextField();
        aktivovatVybrane = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.Menu.setVisible(false);

        jLabel1.setText("Vyberte svuj ucet :");

        jLabel2.setText("Zadejte své heslo");

        vyberUcet.setModel(new javax.swing.DefaultComboBoxModel(uzivatel.nactiUdajeOHracich(1)));
        vyberUcet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberUcetActionPerformed(evt);
            }
        });

        prihlas.setText("Prihlas");
        prihlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasActionPerformed(evt);
            }
        });

        vytvorNovyUcet.setText("Vytvorit novy ucet");
        vytvorNovyUcet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorNovyUcetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrihlaseniLayout = new javax.swing.GroupLayout(Prihlaseni);
        Prihlaseni.setLayout(PrihlaseniLayout);
        PrihlaseniLayout.setHorizontalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrihlaseniLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(vytvorNovyUcet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prihlas))
                    .addGroup(PrihlaseniLayout.createSequentialGroup()
                        .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vyberUcet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PrihlaseniLayout.createSequentialGroup()
                                .addComponent(vstupHesla, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PrihlaseniLayout.setVerticalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vyberUcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vstupHesla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prihlas)
                    .addComponent(vytvorNovyUcet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Zadejte jmeno uctu:");

        jLabel4.setText("Zadejte heslo pro ucet*:");

        jLabel5.setText("Opakujte heslo zadani uctu:");

        vytvorUcetButton.setText("Vytvor");
        vytvorUcetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorUcetButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("* Heslo musi mit delku 4 nebo 6 znaku.");

        zpetDoPrihlas.setText("Zpet");
        zpetDoPrihlas.setMaximumSize(new java.awt.Dimension(65, 23));
        zpetDoPrihlas.setMinimumSize(new java.awt.Dimension(65, 23));
        zpetDoPrihlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetDoPrihlasActionPerformed(evt);
            }
        });

        jmenoUctu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenoUctuActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Vytvoření nového účtu");

        javax.swing.GroupLayout novyUcetLayout = new javax.swing.GroupLayout(novyUcet);
        novyUcet.setLayout(novyUcetLayout);
        novyUcetLayout.setHorizontalGroup(
            novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novyUcetLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(zpetDoPrihlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmenoUctu, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(hesloNovehoUctu)
                    .addComponent(opakovaneHesloNovehoUctu)
                    .addComponent(vytvorUcetButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(novyUcetLayout.createSequentialGroup()
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(novyUcetLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(novyUcetLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel20)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        novyUcetLayout.setVerticalGroup(
            novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novyUcetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jmenoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hesloNovehoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opakovaneHesloNovehoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vytvorUcetButton)
                    .addComponent(zpetDoPrihlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Vyberte slonik s kterym chcete pacovat: ");

        vyberSlovnik.setModel(new javax.swing.DefaultComboBoxModel(slovnik.nactiSeznam()));
        vyberSlovnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberSlovnikActionPerformed(evt);
            }
        });

        potvrdSlovnik.setText("Ok");
        potvrdSlovnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdSlovnikActionPerformed(evt);
            }
        });

        jLabel11.setText("Pridani Slovicek");

        jLabel12.setText("Zadejte cesky vyraz:");

        ceskyVyraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceskyVyrazActionPerformed(evt);
            }
        });

        jLabel13.setText("Zadejte jeho anglicky preklad:");

        Uloz.setText("Uloz");
        Uloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlozActionPerformed(evt);
            }
        });

        spravaSlovicek.setBackground(new java.awt.Color(0, 102, 204));

        jLabel9.setText("Sprava Slovicek");

        pridaniSlovicekButton.setText("Pridani slovicek");
        pridaniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridaniSlovicekButtonActionPerformed(evt);
            }
        });

        smazaniSlovicekButton.setText("Smazani slovicek");
        smazaniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smazaniSlovicekButtonActionPerformed(evt);
            }
        });

        zobrazeniSlovicekButton.setText("Zobrazeni slovicek");
        zobrazeniSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniSlovicekButtonActionPerformed(evt);
            }
        });

        zobrazeniNeaktivnichSlovicekButton.setText("Zobrazeni neaktivnich slovicek");
        zobrazeniNeaktivnichSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazeniNeaktivnichSlovicekButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Zpet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aktivovaniNeaktivnichSlov.setText("Aktivovat neaktivni slovicka");
        aktivovaniNeaktivnichSlov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovaniNeaktivnichSlovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout spravaSlovicekLayout = new javax.swing.GroupLayout(spravaSlovicek);
        spravaSlovicek.setLayout(spravaSlovicekLayout);
        spravaSlovicekLayout.setHorizontalGroup(
            spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addComponent(pridaniSlovicekButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(smazaniSlovicekButton)
                        .addGap(39, 39, 39))
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addComponent(zobrazeniSlovicekButton)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(spravaSlovicekLayout.createSequentialGroup()
                        .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aktivovaniNeaktivnichSlov)
                            .addComponent(zobrazeniNeaktivnichSlovicekButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        spravaSlovicekLayout.setVerticalGroup(
            spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spravaSlovicekLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridaniSlovicekButton)
                    .addComponent(smazaniSlovicekButton))
                .addGap(18, 18, 18)
                .addGroup(spravaSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zobrazeniSlovicekButton)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(zobrazeniNeaktivnichSlovicekButton)
                .addGap(18, 18, 18)
                .addComponent(aktivovaniNeaktivnichSlov)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pridaniSlovicekPanelLayout = new javax.swing.GroupLayout(pridaniSlovicekPanel);
        pridaniSlovicekPanel.setLayout(pridaniSlovicekPanelLayout);
        pridaniSlovicekPanelLayout.setHorizontalGroup(
            pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                .addGroup(pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anglickyVyraz, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pridaniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Uloz))
                    .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                        .addGroup(pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ceskyVyraz, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spravaSlovicek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pridaniSlovicekPanelLayout.setVerticalGroup(
            pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pridaniSlovicekPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(ceskyVyraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spravaSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pridaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(anglickyVyraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Uloz)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout vyberSlovnikPanelLayout = new javax.swing.GroupLayout(vyberSlovnikPanel);
        vyberSlovnikPanel.setLayout(vyberSlovnikPanelLayout);
        vyberSlovnikPanelLayout.setHorizontalGroup(
            vyberSlovnikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyberSlovnikPanelLayout.createSequentialGroup()
                .addComponent(pridaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(vyberSlovnikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vyberSlovnikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vyberSlovnikPanelLayout.createSequentialGroup()
                        .addComponent(vyberSlovnik, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(potvrdSlovnik, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vyberSlovnikPanelLayout.setVerticalGroup(
            vyberSlovnikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyberSlovnikPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vyberSlovnikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potvrdSlovnik)
                    .addComponent(vyberSlovnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(278, 278, 278)
                .addComponent(pridaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(0, 102, 204));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Zkouseni");

        spravaSlovicekButton.setBackground(new java.awt.Color(0, 0, 204));
        spravaSlovicekButton.setForeground(new java.awt.Color(0, 204, 0));
        spravaSlovicekButton.setText("Sprava slovicek");
        spravaSlovicekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spravaSlovicekButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setText("Statistiky");
        jButton3.setMaximumSize(new java.awt.Dimension(146, 46));
        jButton3.setMinimumSize(new java.awt.Dimension(146, 46));

        zmenaSlovniku.setBackground(new java.awt.Color(0, 0, 204));
        zmenaSlovniku.setForeground(new java.awt.Color(0, 204, 0));
        zmenaSlovniku.setText("Zmena slovniku");
        zmenaSlovniku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmenaSlovnikuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Menu");

        odhlasitSe.setBackground(new java.awt.Color(0, 0, 204));
        odhlasitSe.setForeground(new java.awt.Color(0, 204, 0));
        odhlasitSe.setText("Odhlsit se");
        odhlasitSe.setMaximumSize(new java.awt.Dimension(107, 23));
        odhlasitSe.setMinimumSize(new java.awt.Dimension(107, 23));
        odhlasitSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odhlasitSeActionPerformed(evt);
            }
        });

        ukoncitProgram.setBackground(new java.awt.Color(0, 0, 204));
        ukoncitProgram.setForeground(new java.awt.Color(0, 204, 0));
        ukoncitProgram.setText("Ukoncit program");
        ukoncitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukoncitProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spravaSlovicekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odhlasitSe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zmenaSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ukoncitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spravaSlovicekButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(zmenaSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(odhlasitSe, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(ukoncitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel10.setText("Zobrazeni slovicek");

        zobrayeniSlovicekText.setEditable(false);
        zobrayeniSlovicekText.setColumns(20);
        zobrayeniSlovicekText.setRows(5);
        jScrollPane1.setViewportView(zobrayeniSlovicekText);

        jButton7.setText("Zpet");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Prejit do Menu");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        zobrazVse.setText("Zobraz vse");
        zobrazVse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazVseActionPerformed(evt);
            }
        });

        zobrazZvolenouDvojci.setText("Zobraz zvolenou dvojci");
        zobrazZvolenouDvojci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazZvolenouDvojciActionPerformed(evt);
            }
        });

        vyberSlovo.setText("1");
        vyberSlovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberSlovoActionPerformed(evt);
            }
        });

        jLabel17.setText("Zobrazeni neaktivnich slovicek");

        zobrayVseNeaktivni.setText("Zobraz vse");
        zobrayVseNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrayVseNeaktivniActionPerformed(evt);
            }
        });

        zobrayeniNeaktivnichSlov.setEditable(false);
        zobrayeniNeaktivnichSlov.setColumns(20);
        zobrayeniNeaktivnichSlov.setRows(5);
        jScrollPane2.setViewportView(zobrayeniNeaktivnichSlov);

        zpetNeaktivni.setText("Zpet");
        zpetNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetNeaktivniActionPerformed(evt);
            }
        });

        prejitDoMenuNeaktivni.setText("Prejit do Menu");
        prejitDoMenuNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prejitDoMenuNeaktivniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zobrazeniNeaktivnichSlovicekLayout = new javax.swing.GroupLayout(zobrazeniNeaktivnichSlovicek);
        zobrazeniNeaktivnichSlovicek.setLayout(zobrazeniNeaktivnichSlovicekLayout);
        zobrazeniNeaktivnichSlovicekLayout.setHorizontalGroup(
            zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addGroup(zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel17)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(zpetNeaktivni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prejitDoMenuNeaktivni)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zobrayVseNeaktivni)
                .addGap(24, 24, 24))
        );
        zobrazeniNeaktivnichSlovicekLayout.setVerticalGroup(
            zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zobrayVseNeaktivni)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zpetNeaktivni)
                    .addComponent(prejitDoMenuNeaktivni))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout zobrazeniSlovicekPanelLayout = new javax.swing.GroupLayout(zobrazeniSlovicekPanel);
        zobrazeniSlovicekPanel.setLayout(zobrazeniSlovicekPanelLayout);
        zobrazeniSlovicekPanelLayout.setHorizontalGroup(
            zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovicekPanelLayout.createSequentialGroup()
                .addGroup(zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zobrazeniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10))
                    .addGroup(zobrazeniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(zobrazeniSlovicekPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9)
                                .addGap(9, 9, 9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniSlovicekPanelLayout.createSequentialGroup()
                                .addComponent(zobrazVse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zobrazZvolenouDvojci)
                                    .addComponent(vyberSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zobrazeniNeaktivnichSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zobrazeniSlovicekPanelLayout.setVerticalGroup(
            zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addGroup(zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zobrazVse)
                    .addComponent(zobrazZvolenouDvojci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vyberSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(zobrazeniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniSlovicekPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(zobrazeniNeaktivnichSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel14.setText("Mazani Slovicek");

        jLabel15.setText("Cislem vyberete dvojci slovicek ke smazani.");

        jLabel16.setText("Pred provedenim akce se dana dvojce slovicek zabrazi.");

        Smaz.setText("Smaz");
        Smaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmazActionPerformed(evt);
            }
        });

        uplneVymazani.setText("Uplne Vymazani");
        uplneVymazani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplneVymazaniActionPerformed(evt);
            }
        });

        zpetMazaniSlovicek.setText("Zpet");
        zpetMazaniSlovicek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetMazaniSlovicekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mazaniSlovicekPanelLayout = new javax.swing.GroupLayout(mazaniSlovicekPanel);
        mazaniSlovicekPanel.setLayout(mazaniSlovicekPanelLayout);
        mazaniSlovicekPanelLayout.setHorizontalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel14))
                    .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mazaniSlovicekPanelLayout.createSequentialGroup()
                                .addComponent(slovickoKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Smaz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                                .addComponent(uplneVymazani))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mazaniSlovicekPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(zpetMazaniSlovicek)))
                .addContainerGap())
        );
        mazaniSlovicekPanelLayout.setVerticalGroup(
            mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mazaniSlovicekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mazaniSlovicekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slovickoKeSmazani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Smaz)
                    .addComponent(uplneVymazani))
                .addGap(18, 18, 18)
                .addComponent(zpetMazaniSlovicek)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel19.setText("Statistiky");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jLabel18.setText("Aktivace slovicek");

        zobrayeniAktivaceSlovicek.setColumns(20);
        zobrayeniAktivaceSlovicek.setRows(5);
        jScrollPane3.setViewportView(zobrayeniAktivaceSlovicek);

        jButton5.setText("Zpet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Prejit do Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        aktivovatVse.setText("Aktivovat vse");
        aktivovatVse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVseActionPerformed(evt);
            }
        });

        aktivovatVybrane.setText("Aktivovat vybrane");
        aktivovatVybrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivovatVybraneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aktivaceSlovicekLayout = new javax.swing.GroupLayout(aktivaceSlovicek);
        aktivaceSlovicek.setLayout(aktivaceSlovicekLayout);
        aktivaceSlovicekLayout.setHorizontalGroup(
            aktivaceSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(aktivaceSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                        .addComponent(aktivovatVse)
                        .addGap(42, 42, 42)
                        .addComponent(coAktovovat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aktivovatVybrane))
                    .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aktivaceSlovicekLayout.setVerticalGroup(
            aktivaceSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aktivaceSlovicekLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aktivaceSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktivovatVse)
                    .addComponent(coAktovovat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aktivovatVybrane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(aktivaceSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout statistikyLayout = new javax.swing.GroupLayout(statistiky);
        statistiky.setLayout(statistikyLayout);
        statistikyLayout.setHorizontalGroup(
            statistikyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistikyLayout.createSequentialGroup()
                .addGroup(statistikyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statistikyLayout.createSequentialGroup()
                        .addGroup(statistikyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statistikyLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel19))
                            .addGroup(statistikyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statistikyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aktivaceSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        statistikyLayout.setVerticalGroup(
            statistikyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistikyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aktivaceSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(vyberSlovnikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Prihlaseni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(novyUcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(statistiky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(zobrazeniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1576, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statistiky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novyUcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Prihlaseni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vyberSlovnikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(zobrazeniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(mazaniSlovicekPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(777, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vytvorNovyUcetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorNovyUcetActionPerformed
        this.Prihlaseni.setVisible(false);
        this.novyUcet.setVisible(true);
        this.setSize(350, 300);

    }//GEN-LAST:event_vytvorNovyUcetActionPerformed

    private void vyberUcetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberUcetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vyberUcetActionPerformed

    private void prihlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasActionPerformed
        boolean spravne = uzivatel.prihlaseni(this.vyberUcet.getSelectedItem().toString(), String.valueOf(this.vstupHesla.getPassword()), this.vyberUcet.getSelectedIndex());
        if (spravne) {
            this.vstupHesla.setText("");
            this.Prihlaseni.setVisible(false);
            this.vyberSlovnikPanel.setVisible(true);
            this.setSize(250, 150);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Bylo zadano spatne heslo, zbavaji vam " + (3 - this.uzivatel.getPokusy()) + " pokusy", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_prihlasActionPerformed

    private void potvrdSlovnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdSlovnikActionPerformed
        slovnik.nactiSlovnik(this.vyberSlovnik.getSelectedItem().toString(), uzivatel.getJmeno());
      //  slovnik.odstranNeaktivni(0);
        neaktivni.nactiSlovnik(this.slovnik.getTypSlovniku(), this.uzivatel.getJmeno());
        //neaktivni.odstranNeaktivni(1);
        this.setSize(330, 230);
        this.Menu.setVisible(true);
        this.vyberSlovnikPanel.setVisible(false);

    }//GEN-LAST:event_potvrdSlovnikActionPerformed

    private void pridaniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridaniSlovicekButtonActionPerformed
        if (this.uzivatel.testPravomoc(this.slovnik.getTvurceSlovniku(), 2)) {
            this.spravaSlovicek.setVisible(false);
            this.pridaniSlovicekPanel.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_pridaniSlovicekButtonActionPerformed

    private void zobrazeniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniSlovicekButtonActionPerformed
        this.spravaSlovicek.setVisible(false);
        this.zobrazeniSlovicekPanel.setVisible(true);
    }//GEN-LAST:event_zobrazeniSlovicekButtonActionPerformed

    private void zobrazVseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazVseActionPerformed
        String[] slova = slovnik.vypis();
        for (int i = 0; i < slova.length; i++) {
            this.zobrayeniSlovicekText.append(slova[i] + "\n");
        }
    }//GEN-LAST:event_zobrazVseActionPerformed

    private void zobrazZvolenouDvojciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazZvolenouDvojciActionPerformed
        this.zobrayeniSlovicekText.setText(this.slovnik.vypisX(Integer.parseInt(this.vyberSlovo.getText())));
    }//GEN-LAST:event_zobrazZvolenouDvojciActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.zobrazeniSlovicekPanel.setVisible(false);
        this.spravaSlovicek.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.zobrazeniSlovicekPanel.setVisible(false);
        this.Menu.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ceskyVyrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceskyVyrazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceskyVyrazActionPerformed

    private void UlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlozActionPerformed
        this.slovnik.vlozNaKonec(this.anglickyVyraz.getText(), this.ceskyVyraz.getText(), 0, 0, this.slovnik.vytvorNoveIdSlova(), 1);
        this.pridaniSlovicekPanel.setVisible(false);
        this.spravaSlovicek.setVisible(true);
    }//GEN-LAST:event_UlozActionPerformed

    private void smazaniSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smazaniSlovicekButtonActionPerformed
        if (this.uzivatel.testPravomoc(this.slovnik.getTvurceSlovniku(), 1)) {
            this.spravaSlovicek.setVisible(false);
            this.mazaniSlovicekPanel.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_smazaniSlovicekButtonActionPerformed

    private void zpetMazaniSlovicekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetMazaniSlovicekActionPerformed
        this.spravaSlovicek.setVisible(true);
        this.mazaniSlovicekPanel.setVisible(false);
    }//GEN-LAST:event_zpetMazaniSlovicekActionPerformed

    private void SmazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmazActionPerformed
        JOptionPane.showConfirmDialog(rootPane, "Opravdu chcete smazat dvojci slovicek"
                + this.slovnik.vypisX(Integer.getInteger(this.slovickoKeSmazani.getText())), "Chyba!", JOptionPane.OK_CANCEL_OPTION);
        // pokud bude stisknuto ok tak zavolat metodu setAktivita(0)a spustit metodu vzmay neaktivni

    }//GEN-LAST:event_SmazActionPerformed

    private void uplneVymazaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplneVymazaniActionPerformed
        if (this.uzivatel.testPravomoc(this.slovnik.getTvurceSlovniku(), 3)) {
            JOptionPane.showConfirmDialog(rootPane, "Opravdu chcete smazat dvojci slovicek"
                    + this.slovnik.vypisX(Integer.getInteger(this.slovickoKeSmazani.getText())), "Chyba!", JOptionPane.OK_CANCEL_OPTION);
            // pokud bude stisknuto ok tak zavolat metodu slovnik.smaz(this.slovickoKeSmazani.getText())
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_uplneVymazaniActionPerformed

    private void zpetNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetNeaktivniActionPerformed
        this.spravaSlovicek.setVisible(true);
        this.zobrazeniNeaktivnichSlovicek.setVisible(false);
    }//GEN-LAST:event_zpetNeaktivniActionPerformed

    private void prejitDoMenuNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prejitDoMenuNeaktivniActionPerformed
        this.Menu.setVisible(true);
        this.zobrazeniNeaktivnichSlovicek.setVisible(false);
    }//GEN-LAST:event_prejitDoMenuNeaktivniActionPerformed

    private void zobrayVseNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrayVseNeaktivniActionPerformed
        String[] slova = this.neaktivni.vypis();
        System.out.println(this.neaktivni.vypis());
        for (int i = 0; i < slova.length; i++) {
            this.zobrayeniNeaktivnichSlov.append(slova[i] + "\n");
        }



    }//GEN-LAST:event_zobrayVseNeaktivniActionPerformed

    private void zobrazeniNeaktivnichSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazeniNeaktivnichSlovicekButtonActionPerformed
        this.spravaSlovicek.setVisible(false);
        this.zobrazeniNeaktivnichSlovicek.setVisible(true);
    }//GEN-LAST:event_zobrazeniNeaktivnichSlovicekButtonActionPerformed

    private void aktivovaniNeaktivnichSlovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovaniNeaktivnichSlovActionPerformed
        if (this.uzivatel.testPravomoc(this.slovnik.getTvurceSlovniku(), 1)) {
            this.spravaSlovicek.setVisible(false);
            this.mazaniSlovicekPanel.setVisible(true);
            String[] slova = this.neaktivni.vypis();
            for (int i = 0; i < slova.length; i++) {
                this.zobrayeniAktivaceSlovicek.append(slova[i] + "\n");
            }
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Na tuto akci nemate pravomoc!", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_aktivovaniNeaktivnichSlovActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.spravaSlovicek.setVisible(true);
        this.aktivaceSlovicek.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.Menu.setVisible(true);
        this.aktivaceSlovicek.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void aktivovatVseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVseActionPerformed
        this.slovnik.aktivaceDeaktivaceSlova(0, 1);
        JOptionPane.showConfirmDialog(rootPane, "Aktivovano", "Ok!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_aktivovatVseActionPerformed

    private void aktivovatVybraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivovatVybraneActionPerformed
        this.slovnik.aktivaceDeaktivaceSlova(Integer.valueOf(this.coAktovovat.getText()), 1);
        JOptionPane.showConfirmDialog(rootPane, "Aktivovano", "Ok!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_aktivovatVybraneActionPerformed

    private void vyberSlovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberSlovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vyberSlovoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            this.spravaSlovicek.setVisible(false);
            this.Menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ukoncitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukoncitProgramActionPerformed
        this.slovnik.ulozSlovnik(this.uzivatel.getJmeno());
        this.slovnik.vycistiSpojovySeznam();
        System.exit(0);
    }//GEN-LAST:event_ukoncitProgramActionPerformed

    private void odhlasitSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odhlasitSeActionPerformed
        this.slovnik.ulozSlovnik(this.uzivatel.getJmeno());
        this.slovnik.vycistiSpojovySeznam();
        this.Menu.setVisible(false);
        this.Prihlaseni.setVisible(true);
    }//GEN-LAST:event_odhlasitSeActionPerformed

    private void zmenaSlovnikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmenaSlovnikuActionPerformed
        this.slovnik.vycistiSpojovySeznam();
        this.Menu.setVisible(false);
        this.vyberSlovnikPanel.setVisible(true);
    }//GEN-LAST:event_zmenaSlovnikuActionPerformed

    private void spravaSlovicekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spravaSlovicekButtonActionPerformed
        this.Menu.setVisible(false);
        this.spravaSlovicek.setBounds(0, 0, 330, 250);
        this.spravaSlovicek.setVisible(true);
    }//GEN-LAST:event_spravaSlovicekButtonActionPerformed

    private void vyberSlovnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberSlovnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vyberSlovnikActionPerformed

    private void zpetDoPrihlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetDoPrihlasActionPerformed
        this.Prihlaseni.setVisible(true);
        this.novyUcet.setVisible(false);
        this.setSize(250, 200);
    }//GEN-LAST:event_zpetDoPrihlasActionPerformed

    private void vytvorUcetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorUcetButtonActionPerformed
        int uspesnost = uzivatel.vytvorUzivatele(this.jmenoUctu.getText(),
                String.valueOf(this.hesloNovehoUctu.getPassword()), 
                String.valueOf(this.opakovaneHesloNovehoUctu.getPassword()));
        switch (uspesnost) {
            case 0:
            JOptionPane.showMessageDialog(rootPane, "Ucet byl uspesne zalozen");
            this.novyUcet.setVisible(false);
            this.Prihlaseni.setVisible(true);
            this.setSize(250, 200);
            break;
            case 1:
            JOptionPane.showMessageDialog(rootPane, "Jmeno je jiz obsazene prosim vyberte si jine", "Chyba!", JOptionPane.WARNING_MESSAGE);
            break;
            case 2:
            JOptionPane.showMessageDialog(rootPane, "Hesla se neshoduji", "Chyba!", JOptionPane.WARNING_MESSAGE);
            break;
            case 3:
            JOptionPane.showMessageDialog(rootPane, "Heslo nema predepsanou delku", "Chyba!", JOptionPane.WARNING_MESSAGE);
                break;
            case 4:
            JOptionPane.showMessageDialog(rootPane, "Některý z údajů nebyl zadán", "Chyba!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_vytvorUcetButtonActionPerformed

    private void jmenoUctuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenoUctuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenoUctuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StareGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StareGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StareGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StareGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StareGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Prihlaseni;
    private javax.swing.JButton Smaz;
    private javax.swing.JButton Uloz;
    private javax.swing.JPanel aktivaceSlovicek;
    private javax.swing.JToggleButton aktivovaniNeaktivnichSlov;
    private javax.swing.JButton aktivovatVse;
    private javax.swing.JButton aktivovatVybrane;
    private javax.swing.JTextField anglickyVyraz;
    private javax.swing.JTextField ceskyVyraz;
    private javax.swing.JTextField coAktovovat;
    private javax.swing.JPasswordField hesloNovehoUctu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jmenoUctu;
    private javax.swing.JPanel mazaniSlovicekPanel;
    private javax.swing.JPanel novyUcet;
    private javax.swing.JButton odhlasitSe;
    private javax.swing.JPasswordField opakovaneHesloNovehoUctu;
    private javax.swing.JButton potvrdSlovnik;
    private javax.swing.JButton prejitDoMenuNeaktivni;
    private javax.swing.JButton pridaniSlovicekButton;
    private javax.swing.JPanel pridaniSlovicekPanel;
    private javax.swing.JButton prihlas;
    private javax.swing.JTextField slovickoKeSmazani;
    private javax.swing.JButton smazaniSlovicekButton;
    private javax.swing.JPanel spravaSlovicek;
    private javax.swing.JButton spravaSlovicekButton;
    private javax.swing.JPanel statistiky;
    private javax.swing.JButton ukoncitProgram;
    private javax.swing.JButton uplneVymazani;
    private javax.swing.JPasswordField vstupHesla;
    private javax.swing.JComboBox vyberSlovnik;
    private javax.swing.JPanel vyberSlovnikPanel;
    private javax.swing.JTextField vyberSlovo;
    private javax.swing.JComboBox vyberUcet;
    private javax.swing.JButton vytvorNovyUcet;
    private javax.swing.JButton vytvorUcetButton;
    private javax.swing.JButton zmenaSlovniku;
    private javax.swing.JButton zobrayVseNeaktivni;
    private javax.swing.JTextArea zobrayeniAktivaceSlovicek;
    private javax.swing.JTextArea zobrayeniNeaktivnichSlov;
    private javax.swing.JTextArea zobrayeniSlovicekText;
    private javax.swing.JButton zobrazVse;
    private javax.swing.JButton zobrazZvolenouDvojci;
    private javax.swing.JPanel zobrazeniNeaktivnichSlovicek;
    private javax.swing.JButton zobrazeniNeaktivnichSlovicekButton;
    private javax.swing.JButton zobrazeniSlovicekButton;
    private javax.swing.JPanel zobrazeniSlovicekPanel;
    private javax.swing.JButton zpetDoPrihlas;
    private javax.swing.JButton zpetMazaniSlovicek;
    private javax.swing.JButton zpetNeaktivni;
    // End of variables declaration//GEN-END:variables
}
