/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class VytvorNovyUcet extends javax.swing.JPanel {
private Gui gui;
    /**
     * Creates new form VytvorNovyUcet
     */
    public VytvorNovyUcet(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novyUcet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vytvorUcetButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        zpetDoPrihlas = new javax.swing.JButton();
        jmenoUctu = new javax.swing.JTextField();
        hesloNovehoUctu = new javax.swing.JPasswordField();
        opakovaneHesloNovehoUctu = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();

        novyUcet.setBackground(new java.awt.Color(51, 102, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Zadej jméno účtu :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Zadejte heslo pro svůj účet* :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Opakujte zadáni hesla účtu :");

        vytvorUcetButton.setBackground(new java.awt.Color(0, 0, 204));
        vytvorUcetButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vytvorUcetButton.setForeground(new java.awt.Color(0, 204, 0));
        vytvorUcetButton.setText("Vytvor");
        vytvorUcetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorUcetButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("* Heslo musí mít délku 4 nebo 6 znaků.");

        zpetDoPrihlas.setBackground(new java.awt.Color(0, 0, 204));
        zpetDoPrihlas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zpetDoPrihlas.setForeground(new java.awt.Color(0, 204, 0));
        zpetDoPrihlas.setText("Zpet");
        zpetDoPrihlas.setMaximumSize(new java.awt.Dimension(65, 23));
        zpetDoPrihlas.setMinimumSize(new java.awt.Dimension(65, 23));
        zpetDoPrihlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetDoPrihlasActionPerformed(evt);
            }
        });

        jmenoUctu.setBackground(new java.awt.Color(0, 0, 204));
        jmenoUctu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jmenoUctu.setForeground(new java.awt.Color(0, 204, 0));
        jmenoUctu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenoUctuActionPerformed(evt);
            }
        });

        hesloNovehoUctu.setBackground(new java.awt.Color(0, 0, 204));
        hesloNovehoUctu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hesloNovehoUctu.setForeground(new java.awt.Color(0, 204, 0));

        opakovaneHesloNovehoUctu.setBackground(new java.awt.Color(0, 0, 204));
        opakovaneHesloNovehoUctu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        opakovaneHesloNovehoUctu.setForeground(new java.awt.Color(0, 204, 0));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 0));
        jLabel20.setText("Vytvoření nového účtu");

        javax.swing.GroupLayout novyUcetLayout = new javax.swing.GroupLayout(novyUcet);
        novyUcet.setLayout(novyUcetLayout);
        novyUcetLayout.setHorizontalGroup(
            novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novyUcetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, novyUcetLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(novyUcetLayout.createSequentialGroup()
                        .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(novyUcetLayout.createSequentialGroup()
                                .addComponent(zpetDoPrihlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vytvorUcetButton))
                            .addGroup(novyUcetLayout.createSequentialGroup()
                                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hesloNovehoUctu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmenoUctu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opakovaneHesloNovehoUctu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
            .addGroup(novyUcetLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        novyUcetLayout.setVerticalGroup(
            novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novyUcetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(12, 12, 12)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jmenoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hesloNovehoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opakovaneHesloNovehoUctu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(novyUcetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vytvorUcetButton)
                    .addComponent(zpetDoPrihlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(novyUcet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(novyUcet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vytvorUcetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorUcetButtonActionPerformed
        boolean uspesnost = gui.uzivatel.vytvorNeboZmenUzivatele(1,this.jmenoUctu.getText(),
            String.valueOf(this.hesloNovehoUctu.getPassword()),
            String.valueOf(this.opakovaneHesloNovehoUctu.getPassword()));
             if(uspesnost){
                 this.gui.setMyView(1);
             }
    }//GEN-LAST:event_vytvorUcetButtonActionPerformed

    private void zpetDoPrihlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetDoPrihlasActionPerformed
        this.gui.setMyView(1);
    }//GEN-LAST:event_zpetDoPrihlasActionPerformed

    private void jmenoUctuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenoUctuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenoUctuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField hesloNovehoUctu;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jmenoUctu;
    private javax.swing.JPanel novyUcet;
    private javax.swing.JPasswordField opakovaneHesloNovehoUctu;
    private javax.swing.JButton vytvorUcetButton;
    private javax.swing.JButton zpetDoPrihlas;
    // End of variables declaration//GEN-END:variables
}
