/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import java.util.ArrayList;

/**
 *
 * @author Marco
 */
public class ZobrazeniSlovniku extends javax.swing.JPanel {
private Gui gui;
    /**
     * Creates new form ZobrazeniSlovniku
     */
    public ZobrazeniSlovniku(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zobrazeniSlovniku = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaZobrazeniSlovniku = new javax.swing.JTextArea();
        zpetZezobrazeniSlovnku = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        zobrazeniSlovniku.setBackground(new java.awt.Color(51, 102, 255));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 0));
        jLabel32.setText("Zobrazení slovníků");

        textAreaZobrazeniSlovniku.setEditable(false);
        textAreaZobrazeniSlovniku.setBackground(new java.awt.Color(0, 0, 204));
        textAreaZobrazeniSlovniku.setColumns(20);
        textAreaZobrazeniSlovniku.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaZobrazeniSlovniku.setForeground(new java.awt.Color(0, 204, 0));
        textAreaZobrazeniSlovniku.setRows(5);
        jScrollPane6.setViewportView(textAreaZobrazeniSlovniku);

        zpetZezobrazeniSlovnku.setBackground(new java.awt.Color(0, 0, 204));
        zpetZezobrazeniSlovnku.setForeground(new java.awt.Color(0, 204, 0));
        zpetZezobrazeniSlovnku.setText("Zpět");
        zpetZezobrazeniSlovnku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetZezobrazeniSlovnkuActionPerformed(evt);
            }
        });

        jButton1.setText("Zobraz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zobrazeniSlovnikuLayout = new javax.swing.GroupLayout(zobrazeniSlovniku);
        zobrazeniSlovniku.setLayout(zobrazeniSlovnikuLayout);
        zobrazeniSlovnikuLayout.setHorizontalGroup(
            zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                        .addComponent(zpetZezobrazeniSlovnku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel32)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        zobrazeniSlovnikuLayout.setVerticalGroup(
            zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zpetZezobrazeniSlovnku)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zpetZezobrazeniSlovnkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetZezobrazeniSlovnkuActionPerformed
this.gui.setMyView(15);
    }//GEN-LAST:event_zpetZezobrazeniSlovnkuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ArrayList seznam=this.gui.slovnik.getSeznamSlovniku();
        for (int i = 0; i < seznam.size(); i++) {
            this.textAreaZobrazeniSlovniku.append(""+seznam.get(i) +"\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea textAreaZobrazeniSlovniku;
    private javax.swing.JPanel zobrazeniSlovniku;
    private javax.swing.JButton zpetZezobrazeniSlovnku;
    // End of variables declaration//GEN-END:variables
}
