/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

/**
 *
 * @author Marco
 */
public class ZobrazeniNeaktivnichSlovicek extends javax.swing.JPanel {
private Gui gui;

    /**
     * Creates new form ZobrazeniNeaktivnichSlovicek
     */
    public ZobrazeniNeaktivnichSlovicek(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zobrazeniNeaktivnichSlovicek = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        zobrayVseNeaktivni = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        zobrayeniNeaktivnichSlov = new javax.swing.JTextArea();
        zpetNeaktivni = new javax.swing.JButton();
        prejitDoMenuNeaktivni = new javax.swing.JButton();

        jLabel17.setText("Zobrazeni neaktivnich slovicek");

        zobrayVseNeaktivni.setText("Zobraz ");
        zobrayVseNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrayVseNeaktivniActionPerformed(evt);
            }
        });

        zobrayeniNeaktivnichSlov.setEditable(false);
        zobrayeniNeaktivnichSlov.setColumns(20);
        zobrayeniNeaktivnichSlov.setRows(5);
        jScrollPane2.setViewportView(zobrayeniNeaktivnichSlov);

        zpetNeaktivni.setText("Zpet");
        zpetNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetNeaktivniActionPerformed(evt);
            }
        });

        prejitDoMenuNeaktivni.setText("Prejit do Menu");
        prejitDoMenuNeaktivni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prejitDoMenuNeaktivniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zobrazeniNeaktivnichSlovicekLayout = new javax.swing.GroupLayout(zobrazeniNeaktivnichSlovicek);
        zobrazeniNeaktivnichSlovicek.setLayout(zobrazeniNeaktivnichSlovicekLayout);
        zobrazeniNeaktivnichSlovicekLayout.setHorizontalGroup(
            zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addGroup(zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel17)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(zpetNeaktivni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prejitDoMenuNeaktivni))
                    .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(zobrayVseNeaktivni)))
                .addContainerGap())
        );
        zobrazeniNeaktivnichSlovicekLayout.setVerticalGroup(
            zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniNeaktivnichSlovicekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zobrayVseNeaktivni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(zobrazeniNeaktivnichSlovicekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zpetNeaktivni)
                    .addComponent(prejitDoMenuNeaktivni))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniNeaktivnichSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniNeaktivnichSlovicek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zobrayVseNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrayVseNeaktivniActionPerformed
        String[] slova = this.gui.slovnik.vypisNeaktivni();
        for (int i = 0; i < slova.length; i++) {
            this.zobrayeniNeaktivnichSlov.append(slova[i] + "\n");
        }
    }//GEN-LAST:event_zobrayVseNeaktivniActionPerformed

    private void zpetNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetNeaktivniActionPerformed
 this.gui.setMyView(5);     
    }//GEN-LAST:event_zpetNeaktivniActionPerformed

    private void prejitDoMenuNeaktivniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prejitDoMenuNeaktivniActionPerformed
this.gui.setMyView(3);     
    }//GEN-LAST:event_prejitDoMenuNeaktivniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton prejitDoMenuNeaktivni;
    private javax.swing.JButton zobrayVseNeaktivni;
    private javax.swing.JTextArea zobrayeniNeaktivnichSlov;
    private javax.swing.JPanel zobrazeniNeaktivnichSlovicek;
    private javax.swing.JButton zpetNeaktivni;
    // End of variables declaration//GEN-END:variables
}
