/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Semestralka1;

import java.util.ArrayList;

/**
 *
 * @author Marco
 */
public class ZobrazeniSlovniku extends javax.swing.JPanel {
private Gui gui;
    /**
     * Creates new form ZobrazeniSlovniku
     */
    public ZobrazeniSlovniku(Gui gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zobrazeniSlovniku = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaZobrazeniSlovniku = new javax.swing.JTextArea();
        zpetZezobrazeniSlovnku = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel32.setText("Zobrazeni Slovniku");

        textAreaZobrazeniSlovniku.setEditable(false);
        textAreaZobrazeniSlovniku.setColumns(20);
        textAreaZobrazeniSlovniku.setRows(5);
        jScrollPane6.setViewportView(textAreaZobrazeniSlovniku);

        zpetZezobrazeniSlovnku.setText("Zpet");
        zpetZezobrazeniSlovnku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zpetZezobrazeniSlovnkuActionPerformed(evt);
            }
        });

        jButton1.setText("Zobraz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zobrazeniSlovnikuLayout = new javax.swing.GroupLayout(zobrazeniSlovniku);
        zobrazeniSlovniku.setLayout(zobrazeniSlovnikuLayout);
        zobrazeniSlovnikuLayout.setHorizontalGroup(
            zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                        .addComponent(zpetZezobrazeniSlovnku)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniSlovnikuLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniSlovnikuLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zobrazeniSlovnikuLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        zobrazeniSlovnikuLayout.setVerticalGroup(
            zobrazeniSlovnikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zobrazeniSlovnikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zpetZezobrazeniSlovnku)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zobrazeniSlovniku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zpetZezobrazeniSlovnkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zpetZezobrazeniSlovnkuActionPerformed
this.gui.setMyView(15);
    }//GEN-LAST:event_zpetZezobrazeniSlovnkuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ArrayList seznam=this.gui.slovnik.getSeznamSlovniku();
        for (int i = 0; i < seznam.size(); i++) {
            this.textAreaZobrazeniSlovniku.append(""+seznam.get(i) +"\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea textAreaZobrazeniSlovniku;
    private javax.swing.JPanel zobrazeniSlovniku;
    private javax.swing.JButton zpetZezobrazeniSlovnku;
    // End of variables declaration//GEN-END:variables
}
